<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IN-PG0352AV" failures="1" tests="1" name="Language" time="43.907" errors="0" timestamp="02 May 2024 11:29:05 GMT">
  <testcase classname="tests.LanguageTest" name="Languagetest" time="21.108">
    <failure type="java.lang.AssertionError" message="expected [मुख्य कंटेंट देखें] but found [Skip to main content]">
      <![CDATA[java.lang.AssertionError: expected [मुख्य कंटेंट देखें] but found [Skip to main content]
	at tests.LanguageTest.Languagetest(LanguageTest.java:42)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Languagetest -->
</testsuite> <!-- Language -->
